project:
  type: website

website:
  title: "Bioinformatics Practicals I"
  navbar:
    left:
      - bash.qmd
      - python1.qmd
      - python2.qmd
      - python3.qmd
      - python4.qmd

format:
  html:
    theme:
      light: flatly
      dark: darkly
    css: styles.css
    toc: true



