project:
  type: website

website:
  title: "Bioinformatics Practicals I"
  sidebar:
    style: "docked"
    search: true
    contents:
      - index.qmd
      - section: Bash
        contents:
        - text: Unit 1
          href: bash1.qmd
        - text: Unit 2
          href: bash2.qmd
        - text: Unit 3
          href: bash3.qmd
        - text: Unit 4
          href: bash4.qmd
        - text: Reference
          href: bash_reference.qmd
      - section: Python
        contents:
        - text: Unit 1
          href: python1.qmd
        - text: Unit 2
          href: python2.qmd
        - text: Unit 3
          href: python3.qmd
        - text: Unit 4
          href: python4.qmd

format:
  html:
    theme:
      light: flatly
      dark: darkly
    css: styles.css
    toc: true



